# $schema: https://www.schemastore.org/yamllint.json
extends: default
rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  line-length: disable
  truthy:
    check-keys: false
