# $schema: https://www.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-workflows:
    uses: ./.github/workflows/verify-github-workflows.yaml
  verify-workflows-with-local:
    uses: ./.github/workflows/verify-github-workflows.yaml
    with:
      use-local-yamllint-config: true
  yamllint-config:
    permissions:
      contents: read
    runs-on: ubuntu-latest # yamllint already installed in `ubuntu-latest` runner image.
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      - run: yamllint --strict .yamllint.yaml
