# $schema: https://www.schemastore.org/github-workflow.json
name: release-mkdocs

on:
  workflow_call:

jobs:
  mkdocs-gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version-file: .python-version
      - run: pip install -r requirements.txt
      - run: mkdocs build # MkDocs with strict mode => build fails on broken links, etc.
      - run: mkdocs gh-deploy --force # Deploy as GitHub Pages
