# $schema: https://www.schemastore.org/github-workflow.json
name: verify-mkdocs

on:
  workflow_call:
    inputs:
      use-local-yamllint-config:
        required: false
        type: boolean
        default: false
        description: Whether to use the yamllint config already found in the repo.

jobs:
  yamllint:
    permissions:
      contents: read
    runs-on: ubuntu-latest # yamllint already installed in `ubuntu-latest` runner image.
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - run: ${{ inputs.use-local-yamllint-config }} || wget https://raw.githubusercontent.com/Harmelodic/workflows/refs/heads/main/.yamllint.yaml --output-document=.yamllint.yaml
      - run: yamllint --strict docs/
      - run: yamllint --strict mkdocs.yaml
  markdownlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24
        with:
          globs: '**/*.md' # Lint all Markdown files in the project.
  mkdocs-build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version-file: .python-version
      - run: pip install -r requirements.txt
      - run: mkdocs build # Build in strict mode will validate docs.
